Viewer Settings:
  View Distance: 4
  Testing Size:
    - 1
    - 1
Terrain Settings:
  Seed: 32450
  Size: 32
  Height: 2
  Resolution: 1
  ISO Level: 0.5
  Biomes:
    Count: 3
    0:
      Name: "Biome: 1"
      Height: 0.504999995
      Color:
        - 0
        - 0.0192306042
        - 1
    1:
      Name: "Biome: 2"
      Height: 0.870000005
      Color:
        - 0.42632398
        - 0.716346145
        - 0.196306378
    2:
      Name: "Biome: 3"
      Height: 1
      Color:
        - 1
        - 1
        - 1
Noise Settings:
  Offsets:
    - 3.0999999
    - 0
    - 0
  Noise Scale:
    - 1
    - 1
  EXP: 9
  Height Multiplier: 5.5
  Frequency: 2.25999999
  Lacunarity: 1.63
  Persistence: 0.708000004
  Octaves: 6
Light Settings:
  Directional Light:
    Direction:
      - -6.40700006
      - -7.20699978
      - 5.69999981
    Ambient:
      - 1
      - 1
      - 1
    Diffuse:
      - 0.5
      - 0.5
      - 0.5
    Specular:
      - 0.25
      - 0.25
      - 0.25
Erosion Settings:
  Num Droplets: 100000
  Max Steps: 64
  Deposition Rate: 0.200000003
  Erosion Rate: 0.699999988
  Evaporation Rate: 0.0199999996
  Min Slope: 0.00999999978
  Inertia: 0.300000012
  Particle Capacity: 8
  Particle Radius: 4