Viewer Settings:
  View Distance: 4
  Testing Size:
    - 1
    - 1
Terrain Settings:
  Seed: 32450
  Size: 64
  Height: 2
  Resolution: 4
  ISO Level: 0.5
  Color:
    - 0.329400003
    - 0.733299971
    - 0.192100003
Noise Settings:
  Offsets:
    - 3.10299993
    - 0
    - 0
  Noise Scale:
    - 1
    - 1.39999998
  Lacunarity: 2.59200001
  Persistence: 1.352
  Octaves: 8
Light Settings:
  Directional Light:
    Direction:
      - -0.200000003
      - -1
      - -0.300000012
    Ambient:
      - 1
      - 1
      - 1
    Diffuse:
      - 0.5
      - 0.5
      - 0.5
    Specular:
      - 0.25
      - 0.25
      - 0.25
Erosion Settings:
  Num Iterations: 10