Viewer Settings:
  View Distance: 4
  Testing Size:
    - 1
    - 1
Terrain Settings:
  Seed: 26699
  Size: 48
  Height: 2
  Resolution: 1
  ISO Level: 0.5
  Biomes:
    Count: 4
    0:
      Name: "Biome: 1"
      Height: 0.504999995
      Color:
        - 0
        - 0.0192306042
        - 1
    1:
      Name: "Biome: 2"
      Height: 0.851999998
      Color:
        - 0.463596046
        - 0.793269217
        - 0.202131107
    2:
      Name: "Biome: 3"
      Height: 0.939999998
      Color:
        - 0.28342852
        - 0.740384579
        - 0.138822109
    3:
      Name: "Biome: 4"
      Height: 1
      Color:
        - 1
        - 1
        - 1
Noise Settings:
  Offsets:
    - 2.41400003
    - 0
    - -3.33299994
  Noise Scale:
    - 0.611999989
    - 0.582000017
  EXP: 12
  Height Multiplier: 6.204
  Frequency: 1.51800001
  Lacunarity: 0.152999997
  Persistence: 4.48099995
  Octaves: 8
Light Settings:
  Directional Light:
    Direction:
      - -6.40700006
      - -7.20699978
      - 5.69999981
    Ambient:
      - 1
      - 1
      - 1
    Diffuse:
      - 0.5
      - 0.5
      - 0.5
    Specular:
      - 0.25
      - 0.25
      - 0.25
Erosion Settings:
  Num Droplets: 10000
  Max Steps: 24
  Deposition Rate: 0.100000001
  Erosion Rate: 0.899999976
  Evaporation Rate: 0.0125000002
  Min Slope: 0.0500000007
  Inertia: 0.0250000004
  Particle Capacity: 32
  Particle Radius: 2